// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYa-NZsMRA2aeWJUwPESpCJ09lMbNWsN8',
    appId: '1:1082566953133:web:68aa8a09ef56bfc6395e24',
    messagingSenderId: '1082566953133',
    projectId: 'tutor-link-bf2a2',
    authDomain: 'tutor-link-bf2a2.firebaseapp.com',
    storageBucket: 'tutor-link-bf2a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCS04o8PTVwLVbVX91KezkVWUcv3O7pm8',
    appId: '1:1082566953133:android:ae3461e4e5179c33395e24',
    messagingSenderId: '1082566953133',
    projectId: 'tutor-link-bf2a2',
    storageBucket: 'tutor-link-bf2a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHK9s82LMO5IIOJn5jNrd2MJnZM7LsXaM',
    appId: '1:1082566953133:ios:55d6bef48a3f0d6c395e24',
    messagingSenderId: '1082566953133',
    projectId: 'tutor-link-bf2a2',
    storageBucket: 'tutor-link-bf2a2.firebasestorage.app',
    iosBundleId: 'com.example.tutorLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHK9s82LMO5IIOJn5jNrd2MJnZM7LsXaM',
    appId: '1:1082566953133:ios:55d6bef48a3f0d6c395e24',
    messagingSenderId: '1082566953133',
    projectId: 'tutor-link-bf2a2',
    storageBucket: 'tutor-link-bf2a2.firebasestorage.app',
    iosBundleId: 'com.example.tutorLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYa-NZsMRA2aeWJUwPESpCJ09lMbNWsN8',
    appId: '1:1082566953133:web:7978a4366991daf9395e24',
    messagingSenderId: '1082566953133',
    projectId: 'tutor-link-bf2a2',
    authDomain: 'tutor-link-bf2a2.firebaseapp.com',
    storageBucket: 'tutor-link-bf2a2.firebasestorage.app',
  );
}